name: Build and Release Angular App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.1

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4.1.1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build:ci

      - name: Get the last used tag
        id: last_used_tag
        run: |
          # Fetch all tags
          git fetch --tags

          # Find the most recent tag
          LAST_TAG=$(git describe --tags --abbrev=0)
          echo "Last used tag is: $LAST_TAG"

          # Set the tag as output for other steps
          echo "::set-output name=last_tag::$LAST_TAG"

      - name: Use the last used tag
        run: echo "The last used tag is ${{ steps.last_used_tag.outputs.last_tag }}"
