name: Build and Release Angular App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.1

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4.1.1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build:ci

      - name: Increment Version
        id: auto_increment
        run: |
          git fetch --tags
        
          latest_tag=$(git describe --tags --abbrev=0 $(git rev-list --tags --max-count=1) || echo "v0.0.0")
          echo "Latest tag reachable from this commit: $latest_tag"
        
          IFS='.' read -r major minor patch <<<"${latest_tag#v}"

          patch=$((patch + 1))

          new_tag="v$major.$minor.$patch"
          echo "New tag: $new_tag"
          
          echo "::set-output name=new_tag::$new_tag"
          
          git tag $new_tag
          git push origin $new_tag
          
      - name: Create GitHub Release  
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.auto_increment.outputs.new_tag }}  # Reference the tag created in the previous step
          release_name: ${{ steps.auto_increment.outputs.new_tag }}  # Set release name the same as the tag
          body: "Automatically generated release for tag ${{ steps.auto_increment.outputs.new_tag }}"  # Customize release notes
          draft: false  # Set to true if you want to create it as a draft
          prerelease: false  # Set to true if it's a prerelease
