name: Build and Release Angular App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.1

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4.1.1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build:ci

      - name: Get the previous tag
        id: previous_tag
        run: |
          git fetch --tags --all
          CURRENT_COMMIT=$(git rev-parse HEAD)

          PREV_TAG=$(git describe --tags --abbrev=0 HEAD)
          echo "Previous tag is: $PREV_TAG"
          echo "::set-output name=prev_tag::$PREV_TAG"

      - name: Use the previous tag
        run: echo "The previous tag is ${{ steps.previous_tag.outputs.prev_tag }}"
